debug: true
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
spring:
  application:
    name: auth-service
  profiles:
    active: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Tus configuraciones personalizadas separadas de las de Spring
app:
  jwt:
    secret: oH+9q7wdTI5MPQmt5wRelMhO70B6FmEGOanhAPEAGbM=
    expiration: 300000
