server:
  port: 8084

spring:
  application:
    name: gallery-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://${GALLERY_MONGO_USERNAME:root}:${GALLERY_MONGO_PASSWORD:root}@db-gallery:27017/${GALLERY_MONGO_DB_NAME:gallery_db}?authSource=admin}
      host: ${SPRING_DATA_MONGODB_HOST:db-gallery}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:${GALLERY_MONGO_DB_NAME:gallery_db}}
      username: ${SPRING_DATA_MONGODB_USERNAME:${GALLERY_MONGO_USERNAME:root}}
      password: ${SPRING_DATA_MONGODB_PASSWORD:${GALLERY_MONGO_PASSWORD:root}}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
      repositories:
        enabled: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://${GALLERY_MONGO_USERNAME:root}:${GALLERY_MONGO_PASSWORD:root}@db-gallery:27017/${GALLERY_MONGO_DB_NAME:gallery_db}?authSource=admin}
    host: ${SPRING_DATA_MONGODB_HOST:db-gallery}
    port: ${SPRING_DATA_MONGODB_PORT:27017}
    database: ${SPRING_DATA_MONGODB_DATABASE:${GALLERY_MONGO_DB_NAME:gallery_db}}
    username: ${SPRING_DATA_MONGODB_USERNAME:${GALLERY_MONGO_USERNAME:root}}
    password: ${SPRING_DATA_MONGODB_PASSWORD:${GALLERY_MONGO_PASSWORD:root}}
    authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
