# Dockerfile.runtime
FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# Copiamos el JAR ya compilado
COPY services/auth-service/target/auth-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]